--- !ditz.rubyforge.org,2008-03-06/project 
name: jhc
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: jhc
- !ditz.rubyforge.org,2008-03-06/component 
  name: type_checker
- !ditz.rubyforge.org,2008-03-06/component 
  name: user_interface
- !ditz.rubyforge.org,2008-03-06/component 
  name: optimizer
- !ditz.rubyforge.org,2008-03-06/component 
  name: front_end
releases: []

