--- !ditz.rubyforge.org,2008-03-06/project 
name: jhc
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: jhc
- !ditz.rubyforge.org,2008-03-06/component 
  name: type_checker
- !ditz.rubyforge.org,2008-03-06/component 
  name: user_interface
- !ditz.rubyforge.org,2008-03-06/component 
  name: optimizer
- !ditz.rubyforge.org,2008-03-06/component 
  name: front_end
- !ditz.rubyforge.org,2008-03-06/component 
  name: libraries
- !ditz.rubyforge.org,2008-03-06/component 
  name: language
- !ditz.rubyforge.org,2008-03-06/component 
  name: back_end
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.6.0
  status: :released
  release_time: 2009-03-27 08:22:13.520019 Z
  log_events: 
  - - 2009-03-27 08:22:03.507070 Z
    - John Meacham <john@repetae.net>
    - created
    - ""
  - - 2009-03-27 08:22:13.520034 Z
    - John Meacham <john@repetae.net>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 1.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-03-27 08:23:38.978338 Z
    - John Meacham <john@repetae.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.8.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-09 21:58:52.799250 Z
    - John Meacham <john@repetae.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.7.5
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-09 21:59:18.109248 Z
    - John Meacham <john@repetae.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.7.4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-09 21:58:43.629236 Z
    - John Meacham <john@repetae.net>
    - created
    - ""
